upstreamProjects:
  Mule-runtime/mule-api/1.5.2
# Comment public setting to get oldMuleArtifact from private repo till we move them to the public Repo
# Uncomment it after they are copied
#mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
jdkTool: OPEN-JDK17
mavenAdditionalArgs: -P!testJdkWithoutXmlModule
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
    mavenAdditionalArgs: ''
  jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: -P!testJdkWithoutXmlModule