module.name=dsl-api

artifact.export.classPackages=org.mule.runtime.dsl.api,\
                              org.mule.runtime.api.artifact.semantic,\
                              org.mule.runtime.api.artifact.sintax,\
                              org.mule.runtime.dsl.api.component,\
                              org.mule.runtime.dsl.api.component.config,\
                              org.mule.runtime.dsl.api.config,\
                              org.mule.runtime.dsl.internal.parser,\
                              org.mule.runtime.dsl.internal.parser.xml,\
                              org.mule.runtime.dsl.api.xml

#TODO remove exported package org.mule.runtime.dsl.internal.parser.xml and org.mule.runtime.dsl.internal.parser


